version: 2.1

jobs:
  build-and-check:
    docker:
      - image: cimg/node:18.20.5
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: npm install -g pnpm
      - run:
          name: Install dependencies
          command: pnpm install
      - run:
          name: Lint
          command: pnpm lint
      - run:
          name: Build
          command: pnpm build
      - store_artifacts:
          path: .next

workflows:
  verify:
    jobs:
      - build-and-check